name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

# Workflow description
jobs:
  alpine_test_module:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: alpine:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout repository under $GITHUB_WORKSPACE so the job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          apk add --update bash curl git
          git clone https://github.com/space-sh/space.git
          cd space && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which busybox
          which space
          bash --version
          space -V
          space -f ./test/test.yaml /_tests/ -a -a -v4
          
  arch_test_module:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pacman -Sy --noconfirm git which
          git clone https://github.com/space-sh/space.git
          cd space && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -f ./test/test.yaml /_tests/ -a -a -v4

  centos_test_module:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          yum -y update && yum -y install curl git which
          git clone https://github.com/space-sh/space.git
          cd space && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -f ./test/test.yaml /_tests/ -a -a -v4
          
  debianjessie_test_module:
    runs-on: ubuntu-latest
    container: debian:jessie
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          apt-get update -qq && apt-get install -y -qq curl git
          git clone https://github.com/space-sh/space.git
          cd space && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -f ./test/test.yaml /_tests/ -a -a -v4

  debianjessie_curl_test_module:
    runs-on: ubuntu-latest
    container: debian:jessie
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          apt-get update -qq && apt-get install -y -qq curl
          curl -LO https://github.com/space-sh/space/archive/refs/heads/master.tar.gz && mkdir -p ./space_install && tar xzvf "master.tar.gz" -C ./space_install --strip-components=1 && cd ./space_install && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -S -f ./test/test.yaml /_tests/ -a -a -v4

  debianjessie_wget_test_module:
    runs-on: ubuntu-latest
    container: debian:jessie
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          apt-get update -qq && apt-get install -y -qq wget
          wget https://github.com/space-sh/space/archive/refs/heads/master.tar.gz && mkdir -p ./space_install && tar xzvf "master.tar.gz" -C ./space_install --strip-components=1 && cd ./space_install && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -S -f ./test/test.yaml /_tests/ -a -a -v4

  debianlatest_test_module:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          apt-get update -qq && apt-get install -y -qq curl git
          git clone https://github.com/space-sh/space.git
          cd space && ./space /install/ && cd ..
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          which bash
          which space
          bash --version
          space -V
          space -f ./test/test.yaml /_tests/ -a -a -v4
